/* Country Paws browser app. Replace config.js with values from config.example.js. */
const config = window.COUNTRY_PAWS_CONFIG || {};
const hasSupabase = config.supabaseUrl && config.supabaseAnonKey && !config.supabaseUrl.includes('your-project');
const db = hasSupabase ? window.supabase.createClient(config.supabaseUrl, config.supabaseAnonKey) : null;
const services = [{id:'full-groom',name:'Full Groom',description:'Bath, cut, drying and styling tailored to their coat.'},{id:'bath-brush',name:'Bath & Brush',description:'A refreshing wash, blow-dry and thorough brush-out.'},{id:'nail-trim',name:'Nail Trim',description:'Quick, calm nail care for nervous paws too.'},{id:'de-shedding',name:'De-shedding',description:'Extra coat care for seasonal undercoat buildup.'},{id:'senior-care',name:'Senior Dog Care',description:'Patient sessions designed around older dogs.'},{id:'gentle-handling',name:'Gentle Handling',description:'A calm approach for sensitive and first-time pups.'}];
const reviews = [{name:'Kristen B.',text:'My senior German Shepherd was treated patiently and with real care.'},{name:'Kimberly B.F.',text:'My rescue was matted and difficult. Melissa cleaned her up from head to toe.'},{name:'Sydni D.B.',text:'Every single visit, my dog comes back looking like a brand-new puppy.'}];
const $=s=>document.querySelector(s); const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
$('#service-list').innerHTML=services.map((s,i)=>`<article class="service-card"><span class="service-number">0${i+1}</span><h3>${s.name}</h3><p>${s.description}</p></article>`).join('');
$('#service-picker').innerHTML=services.map((s,i)=>`<button type="button" class="service-option${i===0?' active':''}" data-service="${s.id}">${s.name}</button>`).join('');
$('#review-list').innerHTML=reviews.map(r=>`<article class="review-card"><p>“${r.text}”</p><strong>${r.name}</strong></article>`).join('');
let selectedService=services[0].id; document.querySelectorAll('.service-option').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.service-option').forEach(x=>x.classList.remove('active'));b.classList.add('active');selectedService=b.dataset.service}));
const dateInput=$('#booking-date'), timeSelect=$('#booking-time'); dateInput.min=new Date().toISOString().slice(0,10);
async function loadTimes(){const date=dateInput.value;if(!date)return;timeSelect.innerHTML='<option>Loading times…</option>';let slots=[];if(db){const {data,error}=await db.from('availability').select('start_time,end_time').eq('date',date).eq('is_available',true).order('start_time');if(!error&&data)slots=data.map(x=>x.start_time.slice(0,5))}if(!slots.length)slots=['09:00','10:30','12:00','13:30','15:00'];timeSelect.innerHTML=slots.map(t=>`<option value="${t}">${t}</option>`).join('')};dateInput.addEventListener('change',loadTimes);
$('#booking-form').addEventListener('submit',async e=>{e.preventDefault();const msg=$('#booking-message');const payload={service_id:selectedService,appointment_date:dateInput.value,start_time:timeSelect.value,customer_name:$('#customer-name').value,customer_email:$('#customer-email').value,customer_phone:$('#customer-phone').value,dog_name:$('#dog-name').value,notes:$('#booking-notes').value,status:'requested'};if(!db){msg.textContent='Preview mode: add your Supabase values to config.js to enable live booking.';msg.style.color='#a56d00';return}const {error}=await db.from('appointments').insert(payload);msg.textContent=error?'We could not save that request. Please call or text us.':'Request received — Melissa will confirm your appointment shortly.';msg.style.color=error?'#a33':'#507044';if(!error)e.target.reset()});
$('#menu-button').addEventListener('click',()=>{const nav=$('#mobile-nav');nav.classList.toggle('open');$('#menu-button').setAttribute('aria-expanded',nav.classList.contains('open'))});
